version: 2

workflows:
  version: 2
  build:
    jobs:
      - rspec
jobs:
  rspec:
    parallelism: 1
    docker:
      - image: cimg/ruby:2.7.5
        environment:
          TZ: "America/Denver"
          AWS_ACCESS_KEY: foo
          AWS_SECRET_ACCESS_KEY: bar
          AWS_REGION: us-west-2
    steps:
      - run: gem install bundler:1.17.3
      - checkout
      - run: bundle install
      - run: bundle exec rspec
